<#
              ____                                                                              
             6MMMMb\                                                                            
            6M'    `
            MM       ___  __     _____   ___  __ ___  __    ___      ____     _____   ___  __   
            YM.      `MM 6MMb   6MMMMMb  `MM 6MM `MM 6MM  6MMMMb    6MMMMb\  6MMMMMb  `MM 6MMb  
             YMMMMb   MMM9 `Mb 6M'   `Mb  MM69 "  MM69 " 8M'  `Mb  MM'    ` 6M'   `Mb  MMM9 `Mb 
                 `Mb  MM'   MM MM     MM  MM'     MM'        ,oMM  YM.      MM     MM  MM'   MM 
                  MM  MM    MM MM     MM  MM      MM     ,6MM9'MM   YMMMMb  MM     MM  MM    MM 
                  MM  MM    MM MM     MM  MM      MM     MM'   MM       `Mb MM     MM  MM    MM 
            L    ,M9  MM    MM YM.   ,M9  MM      MM     MM.  ,MM  L    ,MM YM.   ,M9  MM    MM 
            MYMMMM9  _MM_  _MM_ YMMMMM9  _MM_    _MM_    `YMMM9'Yb.MYMMMM9   YMMMMM9  _MM_  _MM_
                                                                                                
                                                                                                                                                                                                                              
                                                                                                                                    
                                                                                    
       _                                                                                                                              ___         
      dM.                                                                   68b                                                       `MM         
     ,MMb                 /                                           /     Y89                             /                          MM         
     d'YM.    ___   ___  /M       _____   ___  __    __      ___     /M     ___   _____   ___  __          /M       _____     _____    MM   ____  
    ,P `Mb    `MM    MM /MMMMM   6MMMMMb  `MM 6MMb  6MMb   6MMMMb   /MMMMM  `MM  6MMMMMb  `MM 6MMb        /MMMMM   6MMMMMb   6MMMMMb   MM  6MMMMb\
    d'  YM.    MM    MM  MM     6M'   `Mb  MM69 `MM69 `Mb 8M'  `Mb   MM      MM 6M'   `Mb  MMM9 `Mb        MM     6M'   `Mb 6M'   `Mb  MM MM'    `
   ,P   `Mb    MM    MM  MM     MM     MM  MM'   MM'   MM     ,oMM   MM      MM MM     MM  MM'   MM        MM     MM     MM MM     MM  MM YM.     
   d'    YM.   MM    MM  MM     MM     MM  MM    MM    MM ,6MM9'MM   MM      MM MM     MM  MM    MM        MM     MM     MM MM     MM  MM  YMMMMb 
  ,MMMMMMMMb   MM    MM  MM     MM     MM  MM    MM    MM MM'   MM   MM      MM MM     MM  MM    MM        MM     MM     MM MM     MM  MM      `Mb
  d'      YM.  YM.   MM  YM.  , YM.   ,M9  MM    MM    MM MM.  ,MM   YM.  ,  MM YM.   ,M9  MM    MM        YM.  , YM.   ,M9 YM.   ,M9  MM L    ,MM
_dM_     _dMM_  YMMM9MM_  YMMM9  YMMMMM9  _MM_  _MM_  _MM_`YMMM9'Yb.  YMMM9 _MM_ YMMMMM9  _MM_  _MM_        YMMM9  YMMMMM9   YMMMMM9  _MM_MYMMMM9 
                                                                                                                                                                                                              

(Header generated by https://www.kammerl.de/ascii/AsciiSignature.php - using georgi16)

.SYNOPSIS
  Get all the webhooks from an automation account and display the expiration date

.DESCRIPTION
    First logs on to AzureAccount
    Then gets all the webhooks from an automation account
    Then loops through each webhook and display the expiration date if it is less than 30 days into the future

.INPUTS
  N/A

.OUTPUTS
  Writes to console the API permissions for the User assigned identety in the destination tenant

.NOTES
  Version:        1.0
  Author:         Steen Snorrason
  Creation Date:  2024.01.04
  Purpose/Change: Initial script development
  
.EXAMPLE
  .\Get-allwebhookExpireDates.ps1 -days 30
#>

Param(
    [Parameter(Mandatory = $false)]
    [Int16] $days = 30,
    [Parameter(Mandatory = $false)]
    [String] $SubscriptionId = "",
    [Parameter(Mandatory = $false)]
    [String] $automationAccountName = "",
    [Parameter(Mandatory = $false)]
    [String] $resourceGroupName = ""

)
function Login($SubscriptionId)
{
    $context = Get-AzContext

    if (!$context -or ($context.Subscription.Id -ne $SubscriptionId)) 
    {
        Write-Host "you are not loged in to the correct subscription" -ForegroundColor Red
        Write-Host "use browser popup to login to the correct subscription" -ForegroundColor Red
        Connect-AzAccount -Subscription $SubscriptionId
    } 
    else 
    {
        Write-Host "You Are connects" -ForegroundColor Green
    }
}

# Connect to your Azure account
Login -SubscriptionId $SubscriptionId

# Get all webhooks from your automation account
$webhooks = Get-AzAutomationWebhook -ResourceGroupName $resourceGroupName -AutomationAccountName $automationAccountName

# Loop through each webhook and display the expiration date
foreach ($webhook in $webhooks) {
    # If Expiation time is les than 30 days into the future display the webhook
    if ($webhook.ExpiryTime -lt (Get-Date).AddDays($days)) {
        Write-Output "Webhook Name: $($webhook.Name)"
        Write-Output "Expiration Date: $($webhook.ExpiryTime)"
        write-output "Last Execution: $($webhook.LastInvokedTime)"
        Write-Output "Runbook Name: $($webhook.RunbookName)"
        Write-Output "------------------------"
    }
}
